/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADropdownButton: typeof import('ant-design-vue/es')['DropdownButton']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    DropdownGames: typeof import('./../components/dropdown-games.vue')['default']
    Greet: typeof import('./../components/Greet.vue')['default']
    Home: typeof import('./../pages/home/index.vue')['default']
    MidiReader: typeof import('./../components/midi-reader.vue')['default']
    MidiRules: typeof import('./../pages/midi-rules/index.vue')['default']
    QuickLinks: typeof import('./../pages/quick-links/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongJson: typeof import('./../pages/song-json/index.vue')['default']
    Upload: typeof import('./../components/upload.vue')['default']
  }
}
